name: "CNN Autoencoder Vision Model"
description: "Test model automatically published from GitHub"

authors:
  - name: "Taha Zeeshan"
    email: "tahazeeshan09@gmail.com"

publishing:
  kaggle:
    enabled: true
  huggingface:
    enabled: true
    repo_id: tahaz122/cnn-autoencoder
    private: false
    demo_enabled: true
    space_id: tahaz122/cnn-autoencoder-demo
    demo_task: classification
    inference_function: predict
