# -*- coding: utf-8 -*-
"""datascience_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197n0ZYxk_lQ0tsRP6pGtwniEN6DNEoWl
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %pip install anomalib

import torch
from torch import nn
from anomalib.data import MVTecAD  #anomalib MVtecad dataset
from anomalib.engine import Engine
from torchvision import transforms
engine = Engine(
    accelerator="gpu",
    devices=1
)
device=torch.device("cuda" if torch.cuda.is_available() else "cpu")
transform = transforms.Compose([
    transforms.Resize((256, 256)),
    transforms.ToTensor()
])

#USING THE INTEL ANOMALIB MVTECAD DATASET AND DATALOADER

data = MVTecAD(root="/content/drive/MyDrive",train_batch_size=8,
    eval_batch_size=8 )
data.setup()
print(data.__dict__.keys())



print(len(data.train_data))
print(len(data.test_data))
print(len(data.val_data))

from anomalib.data.dataclasses.torch.base import Batch
loader=data.train_dataloader()



# AUTOENCODER MODEL HAVING ENCODER AND DECODER SETUP WITH CNNS

class Autoencoder(nn.Module):
    def __init__(self):
        super().__init__()
        # Encoder Convolutional Layers
        self.encoder_conv = nn.Sequential(
            nn.Conv2d(3, 32, 4, stride=2, padding=1),   # 256x256 -> 128x128
            nn.ReLU(),
            nn.Conv2d(32, 64, 4, stride=2, padding=1),  # 128x128 -> 64x64
            nn.ReLU(),
            nn.Conv2d(64, 128, 4, stride=2, padding=1), # 64x64 -> 32x32
            nn.ReLU(),
            nn.Conv2d(128, 256, 4, stride=2, padding=1) # 32x32 -> 16x16
        )

        # Tight Linear Bottleneck to force semantic compression (improved the results)
        self.flatten = nn.Flatten()
        self.fc_encode = nn.Linear(256 * 16 * 16, 128)   # Latent vector dimension = 128

        # Decoder Linear Layers
        self.fc_decode = nn.Linear(128, 256 * 16 * 16)
        self.unflatten = nn.Unflatten(1, (256, 16, 16))

        # Decoder Convolutional Layers
        self.decoder_conv = nn.Sequential(
            nn.ConvTranspose2d(256, 128, 4, stride=2, padding=1), # 16x16 -> 32x32
            nn.ReLU(),
            nn.ConvTranspose2d(128, 64, 4, stride=2, padding=1),  # 32x32 -> 64x64
            nn.ReLU(),
            nn.ConvTranspose2d(64, 32, 4, stride=2, padding=1),   # 64x64 -> 128x128
            nn.ReLU(),
            nn.ConvTranspose2d(32, 3, 4, stride=2, padding=1),    # 128x128 -> 256x256
            nn.Sigmoid()
        )

    def forward(self, x):
        # Pass through convolutional encoder
        x = self.encoder_conv(x)
        # Flatten and compress into tight bottleneck
        x = self.flatten(x)
        bottleneck = self.fc_encode(x)

        # Decompress out of bottleneck
        x = self.fc_decode(bottleneck)
        x = self.unflatten(x)
        # Pass through convolutional decoder
        decode = self.decoder_conv(x)
        return decode

from torch.optim import Adam

encoder=Autoencoder()
loss=nn.MSELoss()

optimizer=Adam(encoder.parameters(),lr=0.001)

import torch.nn.functional as F

encoder = Autoencoder().to(device) # Move model to GPU
loss_fn = nn.MSELoss()
optimizer = Adam(encoder.parameters(), lr=0.001)

epochs = 100
for epoch in range(epochs):
    total_loss = 0
    encoder.train()
    for batch_idx, batch in enumerate(loader):
        optimizer.zero_grad()

        # Correctly interpolate on device
        inputs = batch.image.to(device)
        inputs = F.interpolate(inputs, size=(256, 256))

        output = encoder(inputs)
        loss_ = loss_fn(output, inputs)
        loss_.backward()
        optimizer.step()

        total_loss += loss_.item()

    avg_loss = total_loss / len(loader)
    print(f"Epoch: {epoch+1}/{epochs} | Avg Loss: {avg_loss:.6f}")

encoder.eval()

encoder.eval()

train_loader = data.train_dataloader()

with torch.no_grad():
    batch = next(iter(train_loader))

    imgs = batch.image[:8].to(device)
    imgs = F.interpolate(imgs, size=(256,256))

    recon = encoder(imgs)

fig, axes = plt.subplots(2, 8, figsize=(15,4))

for i in range(8):

    orig = imgs[i].cpu().permute(1,2,0)
    rec = recon[i].cpu().permute(1,2,0)

    axes[0,i].imshow(orig)
    axes[0,i].axis("off")

    axes[1,i].imshow(rec)
    axes[1,i].axis("off")

axes[0,0].set_title("Train Original")
axes[1,0].set_title("Train Reconstruction")

plt.tight_layout()
plt.show()

test_loader=data.test_dataloader()

for batch in test_loader:
    print(batch)
    print(batch.__dict__.keys())
    break

import matplotlib.pyplot as plt
import numpy as np

# Set model to evaluation mode
encoder.eval()

test_loss = 0
normal_scores = []
defect_scores = []

# We will collect a few sample images during evaluation to visualize later
sample_originals = []
sample_reconstructions = []
sample_labels = []

with torch.no_grad():
    for batch in test_loader:
        # 1. Correctly move test data to device and resize
        inputs = batch.image.to(device)
        inputs = F.interpolate(inputs, size=(256, 256))
        labels = batch.gt_label

        # 2. Forward pass to get reconstructions
        outputs = encoder(inputs)

        # 3. Calculate global test loss for tracking
        batch_loss = loss_fn(outputs, inputs)
        test_loss += batch_loss.item()

        # 4. Calculating per-pixel MSE
        # Shape: [Batch, 256, 256]
        error_maps = ((inputs - outputs) ** 2).mean(dim=1)

        # Store scores based on true anomaly label (0 = Normal, 1 = Defective)
        for i in range(len(error_maps)):
            max_local_error = error_maps[i].max().item()
            if labels[i] == 0:
                normal_scores.append(max_local_error)
            else:
                defect_scores.append(max_local_error)

        # Save the first batch's worth of images for plotting
        if len(sample_originals) < 4:
            sample_originals.extend(inputs.cpu())
            sample_reconstructions.extend(outputs.cpu())
            sample_labels.extend(labels.numpy())

# Calculate and print overall test metrics
avg_test_loss = test_loss / len(test_loader)
print("==============================")
print(f"Test Dataset Avg Batch Loss: {avg_test_loss:.6f}")
print(f"Train Dataset Avg Batch Loss: {avg_loss:.6f}")

print("==============================")
if normal_scores:
    print(f"Train Samples Max Local Error Range: {min(normal_scores):.4f} -> {max(normal_scores):.4f}")
if defect_scores:
    print(f"Defective Samples Max Local Error Range: {min(defect_scores):.4f} -> {max(defect_scores):.4f}")
print("==============================\n")


# 5. VISUALIZATION CODE: Plot original vs reconstruction vs anomaly map
num_samples = min(4, len(sample_originals))
fig, axes = plt.subplots(num_samples, 3, figsize=(12, 3 * num_samples))

# Fix dimensions if only 1 sample is displayed
if num_samples == 1:
    axes = np.expand_dims(axes, axis=0)

for idx in range(num_samples):
    orig = sample_originals[idx].permute(1, 2, 0).numpy()
    recon = sample_reconstructions[idx].permute(1, 2, 0).numpy()

    # Generate the structural discrepancy heatmap
    diff_map = np.mean((orig - recon) ** 2, axis=-1)

    label_text = "Anomaly" if sample_labels[idx] != 0 else "Normal"

    # Column 1: Original Image
    axes[idx, 0].imshow(orig)
    axes[idx, 0].set_title(f"Original ({label_text})")
    axes[idx, 0].axis("off")

    # Column 2: Network Reconstruction
    axes[idx, 1].imshow(recon)
    axes[idx, 1].set_title("Reconstruction")
    axes[idx, 1].axis("off")

    # Column 3: Error Heatmap (Bright areas show where the defect is caught)
    heatmap = axes[idx, 2].imshow(diff_map, cmap="jet")
    axes[idx, 2].set_title("Defect Map (Discrepancy)")
    axes[idx, 2].axis("off")
    fig.colorbar(heatmap, ax=axes[idx, 2], fraction=0.046, pad=0.04)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))

plt.hist(normal_scores,
         bins=20,
         alpha=0.6,
         label="Normal")

plt.hist(defect_scores,
         bins=20,
         alpha=0.6,
         label="Defective")

plt.xlabel("Reconstruction Error")
plt.ylabel("Number of Images")
plt.title("Normal vs Defective Error Distribution")
plt.legend()

plt.show()

plt.figure(figsize=(6,5))

plt.boxplot(
    [normal_scores, defect_scores],
    labels=["Normal", "Defective"]
)

plt.ylabel("Maximum Reconstruction Error")
plt.title("Error Distribution Comparison")

plt.show()

